name: Destroy
on:
  workflow_dispatch: {}

concurrency:
  group: tf-misinfo-infra
  cancel-in-progress: true

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: eu-north-1
      TFSTATE_BUCKET: misinfo-tfstate-eu-north-1-misinfo
      TFSTATE_KEY: infra/terraform.tfstate
      TF_LOCK_TABLE: misinfo-tf-locks

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        working-directory: infra
        run: |
          set -euo pipefail
          terraform init -lock-timeout=5m \
            -backend-config="bucket=${TFSTATE_BUCKET}" \
            -backend-config="key=${TFSTATE_KEY}" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="dynamodb_table=${TF_LOCK_TABLE}" \
            -backend-config="encrypt=true"

      - name: Terraform destroy
        working-directory: infra
        run: terraform destroy -lock-timeout=5m -auto-approve

